Repository iterate-ch/cyberduck, pull requests merged in 2022-05, with the labels that each got.

#13352 Move OneDriveUrlProvider to GraphUrlProvider, sharing implementation for all Graph protocols
  onedrive/src/main/java/ch/cyberduck/core/onedrive/GraphSession.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/OneDriveSession.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/features/GraphReadFeature.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/features/GraphUrlProvider.java
Labels: sharepoint

#12871 Fix #12870.
  nextcloud/src/main/java/ch/cyberduck/core/nextcloud/NextcloudShareProvider.java
Labels: nextcloud

#13380 Review handling of Google Docs.
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveAttributesFinderFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveCopyFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveDeleteFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveFileIdProvider.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveMoveFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveReadFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveTrashFeature.java
Labels: googledrive

#13399 Register custom DNS resolver to handle IPv6 preference.
  core/src/main/java/ch/cyberduck/core/http/CustomDnsResolver.java
  core/src/main/java/ch/cyberduck/core/http/HttpConnectionPoolBuilder.java
Labels: core

#13387 Skip querying for multipart uploads when disabled in profile.
  s3/src/main/java/ch/cyberduck/core/s3/S3ListService.java
  s3/src/main/java/ch/cyberduck/core/s3/S3WriteFeature.java
Labels: s3

#13382 Implement delete feature using batch delete.
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSBatchDeleteFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSSession.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSThresholdDeleteFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/io/swagger/client/ApiClient.java
  dracoon/src/test/java/ch/cyberduck/core/sds/SDSBatchDeleteFeatureTest.java
Labels: dracoon

#13402 Return empty ACL in case of disabled ACLs.
  pom.xml
  s3/src/main/java/ch/cyberduck/core/s3/S3AccessControlListFeature.java
Labels: s3

#13395 Fix #13359.
  s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java
  s3/src/main/java/ch/cyberduck/core/s3/S3BulkTransferAccelerationFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3TransferAccelerationService.java
  s3/src/test/java/ch/cyberduck/core/s3/S3TransferAccelerationServiceTest.java
Labels: s3

#13405 Fix error reporting to get parser failure.
  s3/src/main/java/ch/cyberduck/core/s3/S3ExceptionMappingService.java
  s3/src/test/java/ch/cyberduck/core/s3/XmlResponsesSaxParserTest.java
Labels: s3

#13398 Fix #13367. Disable conflicting temporary file upload for rename and …
  core/src/main/java/ch/cyberduck/core/transfer/TransferStatus.java
  core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/download/RenameFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/download/ResumeFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/upload/AbstractUploadFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/upload/RenameExistingFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/upload/RenameFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/upload/ResumeFilter.java
  core/src/test/java/ch/cyberduck/core/transfer/upload/OverwriteFilterTest.java
  core/src/test/java/ch/cyberduck/core/transfer/upload/RenameExistingFilterTest.java
  core/src/test/java/ch/cyberduck/core/transfer/upload/RenameFilterTest.java
  core/src/test/java/ch/cyberduck/core/transfer/upload/ResumeFilterTest.java
Labels: core

#13411 Throw original multipart upload failure.
  s3/src/main/java/ch/cyberduck/core/s3/S3ThresholdUploadService.java
Labels: s3
