Repository iterate-ch/cyberduck, pull requests merged in 2022-04, with the labels that each got.

#13032 Make sure to modal session session.
  binding/src/main/java/ch/cyberduck/binding/SheetInvoker.java
Labels: core

#13046 Generate bindings from latest API.
  brick/src/main/java/ch/cyberduck/core/brick/BrickFileMigrationFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/io/swagger/client/model/FileMigrationEntity.java
  brick/src/main/resources/api.json
Labels: files.com

#13024 Show roleSessionName in CloudTrail S3 logs
  s3/src/main/java/ch/cyberduck/core/sts/STSCredentialsConfigurator.java
Labels: s3

#13053 Add test.
  freenet/src/test/java/ch/cyberduck/core/freenet/FreenetFindFeatureTest.java
Labels: freenet

#13059 Release connection on network failure for stateful sessions. Fix regr…
  core/src/main/java/ch/cyberduck/core/pool/StatefulSessionPool.java
  core/src/main/java/ch/cyberduck/core/pool/StatelessSessionPool.java
  core/src/test/java/ch/cyberduck/core/pool/StatefulSessionPoolTest.java
Labels: ftp

#13268 Close random access file prior deleting.
  core/src/main/java/ch/cyberduck/core/io/Buffer.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSDirectS3UploadFeature.java
Labels: dracoon

#13290 Remove non-OAuth bookmark migration
  core/src/main/java/ch/cyberduck/core/preferences/Preferences.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSErrorResponseInterceptor.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSProtocol.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSSession.java
  dracoon/src/main/resources/DRACOON (Active Directory).cyberduckprofile
  dracoon/src/main/resources/DRACOON (Email Address).cyberduckprofile
  dracoon/src/main/resources/DRACOON (Radius).cyberduckprofile
  dracoon/src/test/java/ch/cyberduck/core/AbstractHostCollectionTest.java
  dracoon/src/test/java/ch/cyberduck/core/HostParserTest.java
  dracoon/src/test/java/ch/cyberduck/core/sds/SDSProtocolTest.java
  dracoon/src/test/java/ch/cyberduck/core/sds/SDSSessionTest.java
Labels: dracoon

#13309 For segmented downloads the read feature must support offsets.
  core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java
Labels: dracoon

#13314 Update to upstream dependency.
  ssh/pom.xml
Labels: sftp

#13295 An empty response to MLSD is valid and indicates an empty folder.
  ftp/src/main/java/ch/cyberduck/core/ftp/list/FTPMlsdListResponseReader.java
  ftp/src/test/java/ch/cyberduck/core/ftp/list/FTPMlsdListResponseReaderTest.java
Labels: ftp

#13327 Fix tests.
  spectra/pom.xml
  spectra/src/main/java/ch/cyberduck/core/spectra/SpectraDeleteFeature.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraAttributesFinderFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraBucketListServiceTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraBulkServiceTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraDeleteFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraDirectoryFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraFindFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraMultipleDeleteFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraObjectListServiceTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraReadFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraSessionTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraTouchFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraUploadFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraVersioningFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraWriteFeatureTest.java
  spectra/src/test/java/ch/cyberduck/core/worker/SpectraSingleTransferWorkerTest.java
Labels: spectralogic

#13319 Make sure that querying S3 direct upload supported works in offline mode.
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSSession.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSTouchFeature.java
Labels: dracoon
