Repository iterate-ch/cyberduck, pull requests merged in 2023-07, with the labels that each got.

#14885 Make autoload of vault configurable.
  core/src/main/java/ch/cyberduck/core/vault/DefaultVaultRegistry.java
  core/src/main/java/ch/cyberduck/core/vault/VaultRegistry.java
  defaults/src/main/resources/default.properties
Labels: cryptomator

#14792 Revert looking up directory placeholder file
  Changelog.txt
  backblaze/src/main/java/ch/cyberduck/core/b2/B2ListService.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2ObjectListService.java
  backblaze/src/test/java/ch/cyberduck/core/b2/B2BucketListServiceTest.java
  backblaze/src/test/java/ch/cyberduck/core/b2/B2DirectoryFeatureTest.java
  backblaze/src/test/java/ch/cyberduck/core/b2/B2ObjectListServiceTest.java
  defaults/src/main/resources/default.properties
  www/update/changelog.html
Labels: b2

#14907 Modified timestamp in transfer status needs to be set for existing files too.
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveWriteFeature.java
  googledrive/src/test/java/ch/cyberduck/core/googledrive/DriveWriteFeatureTest.java
Labels: googledrive

#14913 Fix layout, now consistent with other languages.
  i18n/src/main/resources/de.lproj/Preferences.xib
Labels: interface

#14920 Clear error state for the case a retry succeeded.
  backblaze/src/main/java/ch/cyberduck/core/b2/B2LargeUploadWriteFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickMultipartWriteFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSDirectS3MultipartWriteFeature.java
  eue/src/main/java/ch/cyberduck/core/eue/EueMultipartWriteFeature.java
  openstack/src/main/java/ch/cyberduck/core/openstack/SwiftLargeUploadWriteFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3MultipartWriteFeature.java
  storegate/src/main/java/ch/cyberduck/core/storegate/StoregateMultipartWriteFeature.java
Labels: s3, openstack, b2, dracoon, files.com
