Repository iterate-ch/cyberduck, pull requests merged in 2023-11, with the labels that each got.

#15299 Remove DAV module dependency for EC2 session credential receiver impl…
  s3/pom.xml
  s3/src/main/java/ch/cyberduck/core/auth/AWSSessionCredentialsRetriever.java
  s3/src/main/java/ch/cyberduck/core/s3/S3Session.java
  s3/src/test/java/ch/cyberduck/core/auth/AWSSessionCredentialsRetrieverTest.java
Labels: s3

#15313 Fix #15222 for basic profiles with no session token.
  s3/src/main/java/ch/cyberduck/core/s3/S3CredentialsConfigurator.java
  s3/src/test/java/ch/cyberduck/core/s3/S3CredentialsConfiguratorTest.java
Labels: s3

#15318 Disable copy url button for internal shares.
  osx/src/main/java/ch/cyberduck/ui/cocoa/controller/BrowserController.java
  windows/src/main/csharp/ch/cyberduck/ui/controller/BrowserController.cs
Labels: nextcloud, owncloud

#15320 Throw errors as exception with security result code.
  core/dylib/src/main/java/ch/cyberduck/core/KeychainCertificateStore.java
  core/dylib/src/main/java/ch/cyberduck/core/KeychainPasswordStore.java
  core/dylib/src/main/java/ch/cyberduck/core/keychain/SecurityFunctions.java
  core/dylib/src/test/java/ch/cyberduck/core/KeychainCertificateStoreTest.java
  core/dylib/src/test/resources/15135.cer
  osx/src/main/java/ch/cyberduck/ui/cocoa/callback/PromptCertificateIdentityCallback.java
Labels: ftp-tls

#15347 Logging.
  ssh/src/main/java/ch/cyberduck/core/sftp/SFTPSession.java
Labels: sftp

#15349 Revert "Always set owner/group on SFTP Except for Windows." Refactor …
  ssh/src/main/java/ch/cyberduck/core/sftp/SFTPAttributesFinderFeature.java
Labels: sftp

#15348 Fix #15343.
  onedrive/src/main/java/ch/cyberduck/core/onedrive/GraphProtocol.java
Labels: sharepoint

#15388 Ensure returned aliases are unique
  core/src/main/csharp/ch/cyberduck/core/SystemCertificateStore.cs
Labels: mountainduck

#15364 Fix #15363.
  profiles/default/S3 (HTTPS).cyberduckprofile
  s3/src/test/java/ch/cyberduck/core/s3/S3ProtocolTest.java
Labels: s3
