Repository iterate-ch/cyberduck, pull requests merged in 2023-08, with the labels that each got.

#14954 Do not attempt large copy when file size is below segment size.
  backblaze/src/main/java/ch/cyberduck/core/b2/B2Session.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2ThresholdUploadService.java
  backblaze/src/test/java/ch/cyberduck/core/b2/B2ThresholdCopyFeatureTest.java
  defaults/src/main/resources/default.properties
Labels: b2

#14963 Do not cache file id when versioned object listings are disabled.
  backblaze/src/main/java/ch/cyberduck/core/b2/B2AttributesFinderFeature.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2ObjectListService.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2VersionIdProvider.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2WriteFeature.java
  backblaze/src/test/java/ch/cyberduck/core/b2/B2ObjectListServiceTest.java
Labels: b2

#14964 Use static part size for uploads to encrypted vault.
  backblaze/src/main/java/ch/cyberduck/core/b2/B2LargeUploadService.java
  backblaze/src/test/java/ch/cyberduck/core/cryptomator/B2LargeUploadServiceTest.java
Labels: b2

#14965 Cache file id regardless of versioning setting.
  backblaze/src/main/java/ch/cyberduck/core/b2/B2AttributesFinderFeature.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2DeleteFeature.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2ObjectListService.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2VersionIdProvider.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2WriteFeature.java
  backblaze/src/test/java/ch/cyberduck/core/b2/B2ObjectListServiceTest.java
Labels: b2

#14962 From https://developer.apple.com/documentation/appkit/nsapplicationde…
  osx/src/main/java/ch/cyberduck/ui/cocoa/controller/MainController.java
Labels: core

#14882 Refactor AWS 4 signature calculation to request interceptor
  core/src/main/java/ch/cyberduck/core/Credentials.java
  defaults/src/main/resources/default.properties
  s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java
  s3/src/main/java/ch/cyberduck/core/s3/S3BucketRegionRedirectStrategy.java
  s3/src/main/java/ch/cyberduck/core/s3/S3Session.java
  s3/src/main/java/ch/cyberduck/core/s3/S3TokenExpiredResponseInterceptor.java
  s3/src/test/java/ch/cyberduck/core/s3/S3SessionTest.java
  spectra/src/main/java/ch/cyberduck/core/spectra/SpectraBulkService.java
Labels: s3

#14981 Fix #14969.
  core/src/main/java/ch/cyberduck/core/threading/SessionBackgroundAction.java
Labels: ftp, ftp-tls

#15037 Update hostnames and tokens.
  ctera/src/test/java/ch/cyberduck/core/ctera/AbstractCteraTest.java
  ctera/src/test/java/ch/cyberduck/core/ctera/CteraSessionTest.java
Labels: ctera

#15052 Allow custom log4j.xml in application support folder.
  core/src/main/java/ch/cyberduck/core/preferences/Preferences.java
Labels: core

#15047 Review antivirus error handling
  core/src/main/java/ch/cyberduck/core/PathAttributes.java
  core/src/main/java/ch/cyberduck/core/exception/AntiVirusAccessDeniedException.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSAttributesAdapter.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSExceptionMappingService.java
  i18n/src/main/resources/ar.lproj/SDS.strings
  i18n/src/main/resources/bg.lproj/SDS.strings
  i18n/src/main/resources/ca.lproj/SDS.strings
  i18n/src/main/resources/cs.lproj/SDS.strings
  i18n/src/main/resources/cy.lproj/SDS.strings
  i18n/src/main/resources/da.lproj/SDS.strings
  i18n/src/main/resources/de.lproj/SDS.strings
  i18n/src/main/resources/el.lproj/SDS.strings
  i18n/src/main/resources/en.lproj/SDS.strings
  i18n/src/main/resources/es.lproj/SDS.strings
  i18n/src/main/resources/et.lproj/SDS.strings
  i18n/src/main/resources/fi.lproj/SDS.strings
  i18n/src/main/resources/fr.lproj/SDS.strings
  i18n/src/main/resources/he.lproj/SDS.strings
  i18n/src/main/resources/hr.lproj/SDS.strings
  i18n/src/main/resources/hu.lproj/SDS.strings
  i18n/src/main/resources/it.lproj/SDS.strings
  i18n/src/main/resources/ja.lproj/SDS.strings
  i18n/src/main/resources/ka.lproj/SDS.strings
  i18n/src/main/resources/ko.lproj/SDS.strings
  i18n/src/main/resources/lv.lproj/SDS.strings
  i18n/src/main/resources/nl.lproj/SDS.strings
  i18n/src/main/resources/no.lproj/SDS.strings
  i18n/src/main/resources/pl.lproj/SDS.strings
  i18n/src/main/resources/pt_BR.lproj/SDS.strings
  i18n/src/main/resources/pt_PT.lproj/SDS.strings
  i18n/src/main/resources/ro.lproj/SDS.strings
  i18n/src/main/resources/ru.lproj/SDS.strings
  i18n/src/main/resources/sk.lproj/SDS.strings
  i18n/src/main/resources/sl.lproj/SDS.strings
  i18n/src/main/resources/sr.lproj/SDS.strings
  i18n/src/main/resources/sv.lproj/SDS.strings
  i18n/src/main/resources/th.lproj/SDS.strings
  i18n/src/main/resources/tr.lproj/SDS.strings
  i18n/src/main/resources/uk.lproj/SDS.strings
  i18n/src/main/resources/zh_CN.lproj/SDS.strings
  i18n/src/main/resources/zh_TW.lproj/SDS.strings
Labels: dracoon

#13995 Fix #12962
  s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java
  s3/src/main/java/ch/cyberduck/core/s3/S3PresignedUrlProvider.java
  s3/src/main/java/ch/cyberduck/core/s3/S3UrlProvider.java
  s3/src/test/java/ch/cyberduck/core/s3/S3PresignedUrlProviderTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3UrlProviderTest.java
Labels: s3
