Repository iterate-ch/cyberduck, pull requests merged in 2024-07, with the labels that each got.

#16098 Increase `cryptomator.vault.autodetect.filecount` to 10.
  defaults/src/main/resources/default.properties
Labels: cryptomator

#16085 Show original failure listing buckets when fallback to list objects f…
  s3/src/main/java/ch/cyberduck/core/s3/S3ListService.java
Labels: s3

#16099 Ignore ACLs with no owner set.
  s3/src/main/java/ch/cyberduck/core/s3/S3AccessControlListFeature.java
Labels: s3

#16114 Verify alerts are called on TransferController
  windows/src/main/csharp/ch/cyberduck/ui/controller/AsyncController.cs
  windows/src/main/csharp/ch/cyberduck/ui/controller/TransferController.cs
  windows/src/main/csharp/ch/cyberduck/ui/core/IWindowController.cs
  windows/src/main/csharp/ch/cyberduck/ui/winforms/threading/DialogAlertCallback.cs
  windows/src/main/csharp/ch/cyberduck/ui/winforms/threading/DialogRecursiveCallback.cs
  windows/src/main/csharp/ch/cyberduck/ui/winforms/threading/DialogTransferErrorCallback.cs
Labels: bug, interface

#16115 Amend Add forNameOrDefault to ProtocolFactory
  windows/src/main/csharp/ch/cyberduck/ui/controller/PreferencesController.cs
Labels: bug, interface

#16111 Add documentation for ACLs
  ctera/src/main/java/ch/cyberduck/core/ctera/README.md
Labels: ctera

#16079 Require explicit configuration in connection profile
  s3/src/main/java/ch/cyberduck/core/s3/S3PathStyleFallbackAdapter.java
  s3/src/main/java/ch/cyberduck/core/s3/S3Session.java
  s3/src/test/java/ch/cyberduck/core/s3/S3DirectoryFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ObjectListServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3SessionTest.java
  spectra/src/main/java/ch/cyberduck/core/spectra/SpectraSession.java
Labels: s3

#16143 Fix HostKeyController target invocation exception
  windows/src/main/csharp/ch/cyberduck/ui/controller/HostKeyController.cs
Labels: bug, interface

#16145 Preserve fileid as `fildid.cache(file, null)` nullifies it.
  storegate/src/main/java/ch/cyberduck/core/storegate/StoregateMoveFeature.java
Labels: storegate

#16148 Review TransferWindow
  windows/src/main/csharp/ch/cyberduck/ui/ViewModels/SynchronizedObservableObject.cs
  windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransferItemViewModel.cs
  windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransferViewModel.cs
  windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransfersViewModel.cs
  windows/src/main/csharp/ch/cyberduck/ui/controller/TransferController.cs
Labels: bug, interface

#16150 Do not cache results from a canceled list worker as it may be incompl…
  core/src/main/java/ch/cyberduck/core/worker/ListWorker.java
Labels: core

#16168 Notify TransfersWindow to reveal an item
  windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransfersViewModel.cs
  windows/src/main/csharp/ch/cyberduck/ui/controller/TransferController.cs
Labels: interface, enhancement
