Repository iterate-ch/cyberduck, pull requests merged in 2024-03, with the labels that each got.

#15548 Add test.
  s3/src/test/java/ch/cyberduck/core/s3/S3SessionTest.java
  s3/src/test/resources/S3 AWS2 Signature Version (HTTPS).cyberduckprofile
Labels: s3

#15678 Fix interoperability with redirect URI with custom scheme passed as U…
  oauth/src/main/java/ch/cyberduck/core/oauth/BrowserOAuth2AuthorizationCodeProvider.java
Labels: storegate

#15672 Back off either for a raw network socket or connection timeout or if …
  backblaze/src/main/java/ch/cyberduck/core/b2/B2ErrorResponseInterceptor.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2Session.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2WriteFeature.java
  box/src/main/java/ch/cyberduck/core/box/BoxChunkedWriteFeature.java
  box/src/main/java/ch/cyberduck/core/box/BoxSession.java
  box/src/main/java/ch/cyberduck/core/box/BoxWriteFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickSession.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickUnauthorizedRetryStrategy.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickWriteFeature.java
  core/src/main/java/ch/cyberduck/core/http/AbstractHttpWriteFeature.java
  core/src/main/java/ch/cyberduck/core/http/ChainedServiceUnavailableRetryStrategy.java
  core/src/main/java/ch/cyberduck/core/http/CustomConnectionBackoffStrategy.java
  core/src/main/java/ch/cyberduck/core/http/CustomServiceUnavailableRetryStrategy.java
  core/src/main/java/ch/cyberduck/core/http/DelayedHttpEntityCallable.java
  core/src/main/java/ch/cyberduck/core/http/ExecutionCountServiceUnavailableRetryStrategy.java
  core/src/main/java/ch/cyberduck/core/http/ExtendedHttpRequestRetryHandler.java
  core/src/main/java/ch/cyberduck/core/http/HttpConnectionPoolBuilder.java
  core/src/main/java/ch/cyberduck/core/http/HttpSession.java
  ctera/src/main/java/ch/cyberduck/core/ctera/CteraAuthenticationHandler.java
  ctera/src/main/java/ch/cyberduck/core/ctera/CteraSession.java
  defaults/src/main/resources/default.properties
  dracoon/src/main/java/ch/cyberduck/core/sds/PreconditionFailedResponseInterceptor.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSDirectS3WriteFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSSession.java
  dropbox/src/main/java/ch/cyberduck/core/dropbox/DropboxSession.java
  eue/src/main/java/ch/cyberduck/core/eue/EueSession.java
  eue/src/main/java/ch/cyberduck/core/eue/EueWriteFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveSession.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveWriteFeature.java
  googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageSession.java
  googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageWriteFeature.java
  hubic/src/main/java/ch/cyberduck/core/hubic/HubicSession.java
  oauth/src/main/java/ch/cyberduck/core/oauth/OAuth2ErrorResponseInterceptor.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/GraphSession.java
  openstack/src/main/java/ch/cyberduck/core/openstack/SwiftWriteFeature.java
  owncloud/src/main/java/ch/cyberduck/core/owncloud/OwncloudSession.java
  s3/src/main/java/ch/cyberduck/core/s3/S3AuthenticationResponseInterceptor.java
  s3/src/main/java/ch/cyberduck/core/s3/S3Session.java
  s3/src/main/java/ch/cyberduck/core/s3/S3WriteFeature.java
  storegate/src/main/java/ch/cyberduck/core/storegate/StoregateSession.java
  storegate/src/main/java/ch/cyberduck/core/storegate/StoregateWriteFeature.java
  webdav/src/main/java/ch/cyberduck/core/dav/DAVWriteFeature.java
Labels: core

#15705 Add fallback for default scheme handler registration.
  oauth/pom.xml
  oauth/src/main/java/ch/cyberduck/core/oauth/CustomSchemeHandlerOAuth2AuthorizationCodeProvider.java
  oauth/src/test/java/ch/cyberduck/core/oauth/CustomSchemeHandlerOAuth2AuthorizationCodeProviderTest.java
Labels: storegate

#15708 Update to Wix 3.14
  NetFx472.wxs
  cli/src/main/wix/Bootstrapper/duck.bootstrapper.wixproj
  windows/src/main/wix/Bootstrapper/Cyberduck.Bootstrapper.wixproj
Labels: installer

#15726 Fix #15725.
  core/dylib/src/main/java/ch/cyberduck/core/urlhandler/LaunchServicesSchemeHandler.java
  ctera/src/main/java/ch/cyberduck/core/ctera/CteraSession.java
  oauth/src/main/java/ch/cyberduck/core/oauth/CustomSchemeHandlerOAuth2AuthorizationCodeProvider.java
Labels: ctera

#15747 Handle missing cookie in response.
  ctera/src/main/java/ch/cyberduck/core/ctera/CteraAuthenticationHandler.java
Labels: ctera

#15773 Skip common prefix / in object list
  core/src/main/java/ch/cyberduck/core/PathNormalizer.java
  core/src/test/java/ch/cyberduck/core/PathNormalizerTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ObjectListServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3VersionedObjectListServiceTest.java
Labels: s3

#15776 Always include native flag in rename.
  ssh/src/main/java/ch/cyberduck/core/sftp/SFTPMoveFeature.java
Labels: sftp
