Repository iterate-ch/cyberduck, pull requests merged in 2024-11, with the labels that each got.

#16469 Ignore missing permissions
  googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageAccessControlListFeature.java
  googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageVersioningFeature.java
Labels: googlestorage

#16490 Fix crash on async login canceled exception
  windows/src/main/csharp/ch/cyberduck/ui/controller/PromptLoginController.cs
Labels: bug, interface

#16495 Use home feature from derived implementations.
  webdav/src/main/java/ch/cyberduck/core/dav/DAVSession.java
Labels: nextcloud, owncloud

#16473 Fix #16377
  s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java
  s3/src/main/java/ch/cyberduck/core/s3/S3AWS4SignatureRequestInterceptor.java
  s3/src/main/java/ch/cyberduck/core/s3/S3BucketRegionRedirectStrategy.java
  s3/src/main/java/ch/cyberduck/core/s3/S3LocationFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3Session.java
  s3/src/main/java/ch/cyberduck/core/sts/STSExceptionMappingService.java
  s3/src/test/java/ch/cyberduck/core/s3/RequestEntityRestStorageServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3AccessControlListFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3AttributesFinderFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3DirectoryFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MoveFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MultipleDeleteFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ReadFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3SessionTest.java
Labels: s3

#16505 Fix #14101.
  core/src/main/java/ch/cyberduck/core/worker/DeleteWorker.java
Labels: cryptomator

#16508 Fix #16472.
  s3/src/main/java/ch/cyberduck/core/s3/S3VersionedObjectListService.java
Labels: s3

#16517 Pull localization changes from Transifex
  i18n/src/main/resources/it.lproj/Support.strings
Labels: localization

#13409 Review URI encoding of key
  core/src/test/java/ch/cyberduck/core/URIEncoderTest.java
  pom.xml
  s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ReadFeatureTest.java
Labels: s3

#16516 Review directory features requiring pseudo file based implementation
  box/src/main/java/ch/cyberduck/core/box/BoxDirectoryFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickDirectoryFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickTouchFeature.java
  core/src/main/java/ch/cyberduck/core/features/Directory.java
  core/src/main/java/ch/cyberduck/core/features/Touch.java
  core/src/test/java/ch/cyberduck/core/NullDirectoryFeature.java
  core/src/test/java/ch/cyberduck/core/worker/MoveWorkerTest.java
  cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoDirectoryV6Feature.java
  cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoDirectoryV7Feature.java
  cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoTouchFeature.java
  cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoChecksumComputeTest.java
  cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoOutputStreamTest.java
  cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoVaultTest.java
  cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoWriteFeatureTest.java
  cryptomator/src/test/java/ch/cyberduck/core/cryptomator/features/CryptoBulkFeatureTest.java
  deepbox/src/main/java/ch/cyberduck/core/deepbox/DeepboxDirectoryFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSDirectoryFeature.java
  dropbox/src/main/java/ch/cyberduck/core/dropbox/DropboxDirectoryFeature.java
  eue/src/main/java/ch/cyberduck/core/eue/EueDirectoryFeature.java
  ftp/src/main/java/ch/cyberduck/core/ftp/FTPDirectoryFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveDirectoryFeature.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveTouchFeature.java
  googlestorage/src/test/java/ch/cyberduck/core/cryptomator/GoogleStorageListServiceTest.java
  irods/src/main/java/ch/cyberduck/core/irods/IRODSDirectoryFeature.java
  irods/src/main/java/ch/cyberduck/core/irods/IRODSTouchFeature.java
  manta/src/main/java/ch/cyberduck/core/manta/MantaDirectoryFeature.java
  manta/src/main/java/ch/cyberduck/core/manta/MantaTouchFeature.java
  nio/src/main/java/ch/cyberduck/core/nio/LocalDirectoryFeature.java
  nio/src/main/java/ch/cyberduck/core/nio/LocalTouchFeature.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/features/GraphDirectoryFeature.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/features/GraphTouchFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBDirectoryFeature.java
  ssh/src/main/java/ch/cyberduck/core/sftp/SFTPDirectoryFeature.java
  ssh/src/main/java/ch/cyberduck/core/sftp/SFTPTouchFeature.java
  storegate/src/main/java/ch/cyberduck/core/storegate/StoregateDirectoryFeature.java
  webdav/src/main/java/ch/cyberduck/core/dav/DAVDirectoryFeature.java
Labels: cryptomator

#16538 Do not persist `--debug` flag in preferences.
  cli/src/main/java/ch/cyberduck/cli/TerminalPreferences.java
Labels: cli

#16545 Add missing chunk.
  deepbox/src/main/java/ch/cyberduck/core/deepbox/DeepboxListService.java
Labels: deepbox

#16556 Synchronize access to in memory tokens
  brick/src/main/java/ch/cyberduck/core/brick/BrickUnauthorizedRetryStrategy.java
  ctera/src/main/java/ch/cyberduck/core/ctera/CteraAuthenticationHandler.java
  oauth/src/main/java/ch/cyberduck/core/oauth/OAuth2RequestInterceptor.java
  s3/src/main/java/ch/cyberduck/core/sts/STSAssumeRoleCredentialsRequestInterceptor.java
Labels: s3, googledrive, googlestorage, onedrive, dracoon, box, sharepoint, ctera

#16552 Fix #16551.
  s3/src/main/java/ch/cyberduck/core/s3/S3UrlProvider.java
Labels: s3

#16471 For stateful connections (FTP) limit to a maximum of 5 connections lo…
  core/src/main/java/ch/cyberduck/core/pool/DefaultSessionPool.java
  defaults/src/main/resources/default.properties
Labels: ftp

#16557 Fix #15422.
  core/src/main/java/ch/cyberduck/core/transfer/CopyTransfer.java
Labels: cryptomator

#16560 Refactor handling of security scoped bookmarks
  core/dylib/src/main/java/ch/cyberduck/core/local/AbstractPromptBookmarkResolver.java
  core/dylib/src/main/java/ch/cyberduck/core/local/FilesystemBookmarkResolverFactory.java
  core/dylib/src/main/java/ch/cyberduck/core/local/FinderLocal.java
  core/dylib/src/test/java/ch/cyberduck/core/local/AliasFilesystemBookmarkResolverTest.java
  core/dylib/src/test/java/ch/cyberduck/core/local/FinderLocalTest.java
  core/dylib/src/test/java/ch/cyberduck/core/local/SecurityScopedFilesystemBookmarkResolverTest.java
  core/src/main/java/ch/cyberduck/core/Local.java
  core/src/main/java/ch/cyberduck/core/local/DisabledFilesystemBookmarkResolver.java
  core/src/main/java/ch/cyberduck/core/local/FilesystemBookmarkResolver.java
  core/src/test/java/ch/cyberduck/core/local/DisabledFilesystemBookmarkResolverTest.java
Labels: core

#16575 Always set maxPartCount parameter.
  backblaze/src/main/java/ch/cyberduck/core/b2/B2LargeUploadPartService.java
Labels: b2

#16561 Feature flags
  azure/src/main/java/ch/cyberduck/core/azure/AzureWriteFeature.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2WriteFeature.java
  box/src/main/java/ch/cyberduck/core/box/BoxChunkedWriteFeature.java
  box/src/main/java/ch/cyberduck/core/box/BoxWriteFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickMultipartWriteFeature.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickWriteFeature.java
  core/src/main/java/ch/cyberduck/core/features/Read.java
  core/src/main/java/ch/cyberduck/core/features/Write.java
  deepbox/src/main/java/ch/cyberduck/core/deepbox/DeepboxWriteFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/triplecrypt/TripleCryptReadFeature.java
  eue/src/main/java/ch/cyberduck/core/eue/EueWriteFeature.java
  ftp/src/main/java/ch/cyberduck/core/ftp/FTPReadFeature.java
  ftp/src/main/java/ch/cyberduck/core/ftp/FTPSession.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveWriteFeature.java
  googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageWriteFeature.java
  nextcloud/src/main/java/ch/cyberduck/core/nextcloud/NextcloudWriteFeature.java
  openstack/src/main/java/ch/cyberduck/core/openstack/SwiftWriteFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3WriteFeature.java
  spectra/src/main/java/ch/cyberduck/core/spectra/SpectraReadFeature.java
  spectra/src/test/java/ch/cyberduck/core/spectra/SpectraReadFeatureTest.java
  tus/src/main/java/ch/cyberduck/core/tus/TusWriteFeature.java
Labels: core

#16563 Add mapping for NSPopover
  binding/src/main/java/ch/cyberduck/binding/application/NSPopover.java
  binding/src/main/java/ch/cyberduck/binding/application/NSView.java
  binding/src/main/java/ch/cyberduck/binding/application/NSViewController.java
Labels: core

#16578 Fix #16334.
  s3/src/main/java/ch/cyberduck/core/s3/S3UrlProvider.java
Labels: s3

#16566 Load protocols using service loader.
  azure/src/main/java/ch/cyberduck/core/azure/AzureProtocol.java
  backblaze/src/main/java/ch/cyberduck/core/b2/B2Protocol.java
  box/src/main/java/ch/cyberduck/core/box/BoxProtocol.java
  brick/src/main/java/ch/cyberduck/core/brick/BrickProtocol.java
  cli/src/main/java/ch/cyberduck/cli/Terminal.java
  core/pom.xml
  core/src/main/csharp/ch/cyberduck/core/serviceloader/AppContextServiceLoader.cs
  core/src/main/java/ch/cyberduck/core/preferences/Preferences.java
  core/src/main/java/ch/cyberduck/core/serviceloader/AnnotationAutoServiceLoader.java
  core/src/main/java/ch/cyberduck/core/serviceloader/AutoServiceLoader.java
  core/src/main/java/ch/cyberduck/core/serviceloader/AutoServiceLoaderFactory.java
  ctera/src/main/java/ch/cyberduck/core/ctera/CteraProtocol.java
  deepbox/src/main/java/ch/cyberduck/core/deepbox/DeepboxProtocol.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSProtocol.java
  dropbox/src/main/java/ch/cyberduck/core/dropbox/DropboxProtocol.java
  eue/src/main/java/ch/cyberduck/core/eue/EueProtocol.java
  freenet/src/main/java/ch/cyberduck/core/freenet/FreenetProtocol.java
  ftp/src/main/java/ch/cyberduck/core/ftp/FTPProtocol.java
  ftp/src/main/java/ch/cyberduck/core/ftp/FTPTLSProtocol.java
  googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveProtocol.java
  googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageProtocol.java
  hubic/src/main/java/ch/cyberduck/core/hubic/HubicProtocol.java
  irods/src/main/java/ch/cyberduck/core/irods/IRODSProtocol.java
  manta/src/main/java/ch/cyberduck/core/manta/MantaProtocol.java
  nextcloud/src/main/java/ch/cyberduck/core/nextcloud/NextcloudProtocol.java
  nio/src/main/java/ch/cyberduck/core/nio/LocalProtocol.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/OneDriveProtocol.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/SharepointProtocol.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/SharepointSiteProtocol.java
  openstack/src/main/java/ch/cyberduck/core/openstack/SwiftProtocol.java
  osx/src/main/java/ch/cyberduck/ui/cocoa/MainApplication.java
  owncloud/src/main/java/ch/cyberduck/core/owncloud/OwncloudProtocol.java
  pom.xml
  s3/src/main/java/ch/cyberduck/core/s3/S3Protocol.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBProtocol.java
  spectra/src/main/java/ch/cyberduck/core/spectra/SpectraProtocol.java
  ssh/src/main/java/ch/cyberduck/core/sftp/SFTPProtocol.java
  storegate/src/main/java/ch/cyberduck/core/storegate/StoregateProtocol.java
  webdav/src/main/java/ch/cyberduck/core/dav/DAVProtocol.java
  webdav/src/main/java/ch/cyberduck/core/dav/DAVSSLProtocol.java
  windows/src/main/csharp/ch/cyberduck/ui/controller/MainController.cs
  windows/src/main/csharp/ch/cyberduck/ui/core/preferences/ApplicationPreferences.cs
Labels: core

#16569 Transfer progress in Finder
  binding/src/main/java/ch/cyberduck/binding/foundation/NSProgress.java
  cli/osx/src/main/java/ch/cyberduck/core/preferences/ApplicationTerminalPreferences.java
  core/dylib/src/main/java/ch/cyberduck/core/local/FinderProgressIconService.java
  core/dylib/src/main/java/ch/cyberduck/core/local/WorkspaceIconService.java
  core/dylib/src/main/java/ch/cyberduck/core/preferences/ApplicationPreferences.java
  core/dylib/src/test/java/ch/cyberduck/core/local/WorkspaceIconServiceTest.java
  core/src/main/java/ch/cyberduck/core/local/DisabledIconService.java
  core/src/main/java/ch/cyberduck/core/local/IconService.java
  core/src/main/java/ch/cyberduck/core/local/IconServiceFactory.java
  core/src/main/java/ch/cyberduck/core/proxy/DisabledProxyFinder.java
  core/src/main/java/ch/cyberduck/core/transfer/CopyTransfer.java
  core/src/main/java/ch/cyberduck/core/transfer/DownloadTransfer.java
  core/src/main/java/ch/cyberduck/core/transfer/SyncTransfer.java
  core/src/main/java/ch/cyberduck/core/transfer/Transfer.java
  core/src/main/java/ch/cyberduck/core/transfer/TransferProgress.java
  core/src/main/java/ch/cyberduck/core/transfer/UploadTransfer.java
  core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java
  core/src/main/java/ch/cyberduck/core/transfer/download/DownloadFilterOptions.java
  core/src/main/java/ch/cyberduck/core/transfer/download/IconServiceStreamListener.java
  core/src/main/java/ch/cyberduck/core/transfer/download/IconUpdateStreamListener.java
  core/src/main/java/ch/cyberduck/core/worker/AbstractTransferWorker.java
  core/src/test/java/ch/cyberduck/core/transfer/UploadTransferTest.java
  core/src/test/java/ch/cyberduck/core/transfer/download/RenameExistingFilterTest.java
  core/src/test/java/ch/cyberduck/core/worker/ConcurrentTransferWorkerTest.java
  core/src/test/java/ch/cyberduck/core/worker/SingleTransferWorkerTest.java
  defaults/src/main/resources/default.properties
  osx/src/main/java/ch/cyberduck/ui/cocoa/datasource/BrowserTableDataSource.java
  s3/src/main/java/ch/cyberduck/core/s3/S3UrlProvider.java
Labels: interface

#16592 Pull localization changes from Transifex
  i18n/src/main/resources/ar.lproj/Status.strings
  i18n/src/main/resources/bg.lproj/Status.strings
  i18n/src/main/resources/ca.lproj/Status.strings
  i18n/src/main/resources/cs.lproj/Status.strings
  i18n/src/main/resources/cy.lproj/Status.strings
  i18n/src/main/resources/da.lproj/Status.strings
  i18n/src/main/resources/de.lproj/Status.strings
  i18n/src/main/resources/el.lproj/Status.strings
  i18n/src/main/resources/es.lproj/Status.strings
  i18n/src/main/resources/et.lproj/Status.strings
  i18n/src/main/resources/fi.lproj/Status.strings
  i18n/src/main/resources/fr.lproj/Status.strings
  i18n/src/main/resources/he.lproj/Status.strings
  i18n/src/main/resources/hr.lproj/Status.strings
  i18n/src/main/resources/hu.lproj/Status.strings
  i18n/src/main/resources/it.lproj/Status.strings
  i18n/src/main/resources/zh_TW.lproj/InfoPlist.strings
  i18n/src/main/resources/zh_TW.lproj/License.strings
  i18n/src/main/resources/zh_TW.lproj/Share.strings
  i18n/src/main/resources/zh_TW.lproj/Updater.strings
Labels: localization

#16599 Cache passphrase to avoid expensive unlock operation.
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSMissingFileKeysSchedulerFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSSession.java
  dracoon/src/main/java/ch/cyberduck/core/sds/SDSShareFeature.java
  dracoon/src/main/java/ch/cyberduck/core/sds/triplecrypt/TripleCryptReadFeature.java
Labels: dracoon
