Repository iterate-ch/cyberduck, pull requests merged in 2024-01, with the labels that each got.

#15513 Sort groups alphabetically.
  core/src/main/java/ch/cyberduck/core/AbstractHostCollection.java
  core/src/test/java/ch/cyberduck/core/AbstractHostCollectionTest.java
Labels: interface

#15516 Add mapping for permissions.
  brick/src/main/java/ch/cyberduck/core/brick/BrickAttributesFinderFeature.java
Labels: files.com

#15524 Add option to retrieve Shell Icon
  core/native/refresh/src/main/csharp/Cyberduck.Core.Refresh.csproj
  core/native/refresh/src/main/csharp/NativeMethods.json
  core/native/refresh/src/main/csharp/NativeMethods.txt
  core/native/refresh/src/main/csharp/Services/IconProvider.cs
  core/native/refresh/src/main/csharp/Services/Win32IconProvider.cs
  core/native/refresh/src/main/csharp/Services/WinFormsIconProvider.cs
  core/native/refresh/src/main/csharp/Services/WpfIconProvider.cs
  core/native/refresh/src/main/csharp/Windows/Win32/CoreRefreshMethods.cs
  core/native/refresh/src/main/csharp/Windows/Win32/FriendlyOverloadExtensions.cs
Labels: interface, feature, mountainduck

#15526 Fix permission mapping.
  brick/src/main/java/ch/cyberduck/core/brick/BrickAttributesFinderFeature.java
Labels: files.com

#15532 Pull localization changes from Transifex
  i18n/src/main/resources/ar.lproj/Browser.xib
  i18n/src/main/resources/bg.lproj/Preferences.xib
  i18n/src/main/resources/ca.lproj/Preferences.xib
  i18n/src/main/resources/cs.lproj/Preferences.xib
  i18n/src/main/resources/cs.lproj/S3.strings
  i18n/src/main/resources/cs.lproj/SDS.strings
  i18n/src/main/resources/cy.lproj/Preferences.xib
  i18n/src/main/resources/de.lproj/InfoPlist.strings
  i18n/src/main/resources/de.lproj/Preferences.xib
  i18n/src/main/resources/el.lproj/Preferences.xib
  i18n/src/main/resources/es.lproj/Preferences.xib
  i18n/src/main/resources/et.lproj/Preferences.xib
  i18n/src/main/resources/fi.lproj/Preferences.xib
  i18n/src/main/resources/fr.lproj/Preferences.xib
  i18n/src/main/resources/hr.lproj/InfoPlist.strings
  i18n/src/main/resources/hr.lproj/Preferences.xib
  i18n/src/main/resources/hr.lproj/S3.strings
  i18n/src/main/resources/hr.lproj/SDS.strings
  i18n/src/main/resources/hu.lproj/Preferences.xib
  i18n/src/main/resources/it.lproj/Preferences.xib
  i18n/src/main/resources/it.lproj/S3.strings
  i18n/src/main/resources/it.lproj/SDS.strings
  i18n/src/main/resources/ka.lproj/Preferences.xib
  i18n/src/main/resources/ko.lproj/InfoPlist.strings
  i18n/src/main/resources/lv.lproj/Preferences.xib
  i18n/src/main/resources/nl.lproj/InfoPlist.strings
  i18n/src/main/resources/pl.lproj/InfoPlist.strings
  i18n/src/main/resources/pl.lproj/Preferences.xib
  i18n/src/main/resources/pt_BR.lproj/Preferences.xib
  i18n/src/main/resources/pt_PT.lproj/Preferences.xib
  i18n/src/main/resources/ru.lproj/InfoPlist.strings
  i18n/src/main/resources/ru.lproj/Preferences.xib
  i18n/src/main/resources/sk.lproj/Preferences.xib
  i18n/src/main/resources/sl.lproj/Preferences.xib
  i18n/src/main/resources/sr.lproj/Preferences.xib
  i18n/src/main/resources/sv.lproj/SDS.strings
  i18n/src/main/resources/th.lproj/Preferences.xib
  i18n/src/main/resources/tr.lproj/InfoPlist.strings
  i18n/src/main/resources/tr.lproj/Preferences.xib
  i18n/src/main/resources/tr.lproj/S3.strings
  i18n/src/main/resources/tr.lproj/SDS.strings
  i18n/src/main/resources/uk.lproj/Preferences.xib
  i18n/src/main/resources/zh_CN.lproj/InfoPlist.strings
  i18n/src/main/resources/zh_TW.lproj/InfoPlist.strings
  i18n/src/main/resources/zh_TW.lproj/Preferences.xib
Labels: localization

#15545 Vault factory for path only.
  core/src/main/java/ch/cyberduck/core/vault/VaultFactory.java
Labels: cryptomator

#15553 Redirect URI is set as query parameter and characters are escaped.
  oauth/src/main/java/ch/cyberduck/core/oauth/OAuth2AuthorizationService.java
Labels: storegate

#15570 Keep Decoder information for Gifs
  core/native/refresh/src/main/csharp/Services/WpfIconProvider.cs
Labels: core

#15561 Make sure to include custom attributes in return value of touch and m…
  nextcloud/src/main/java/ch/cyberduck/core/nextcloud/NextcloudSession.java
  nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudAttributesFinderFeatureTest.java
  nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudListServiceTest.java
  nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudShareFeatureTest.java
  nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudVersioningFeatureTest.java
  owncloud/src/main/java/ch/cyberduck/core/owncloud/OwncloudSession.java
  webdav/src/main/java/ch/cyberduck/core/dav/DAVDirectoryFeature.java
  webdav/src/main/java/ch/cyberduck/core/dav/DAVTouchFeature.java
Labels: nextcloud, owncloud

#15591 Add default caching fileid implementation creating random values
  box/src/main/java/ch/cyberduck/core/box/BoxSession.java
  core/src/main/java/ch/cyberduck/core/Session.java
  core/src/main/java/ch/cyberduck/core/shared/RandomFileIdProvider.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/GraphSession.java
  onedrive/src/main/java/ch/cyberduck/core/onedrive/SharepointSiteSession.java
Labels: core

#15589 Rewrite to use pool for disk shares in use.
  smb/src/main/java/ch/cyberduck/core/smb/SMBAttributesFinderFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBCopyFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBDeleteFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBDirectoryFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBFindFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBListService.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBMoveFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBReadFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBSession.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBTimestampFeature.java
  smb/src/main/java/ch/cyberduck/core/smb/SMBWriteFeature.java
Labels: smb
