Repository iterate-ch/cyberduck, pull requests merged in 2024-09, with the labels that each got.

#16274 IgnoreColorProfile was necessary for some systems
  core/native/refresh/src/main/csharp/Services/WpfIconProvider.cs
Labels: bug, interface

#16275 Fix #16267.
  s3/src/main/java/ch/cyberduck/core/s3/S3VersioningFeature.java
Labels: s3

#16283 Fix #16247.
  binding/src/main/java/ch/cyberduck/binding/AbstractTableDelegate.java
  binding/src/main/java/ch/cyberduck/binding/application/NSAccessibility.java
  binding/src/main/java/ch/cyberduck/binding/application/NSCell.java
  binding/src/main/java/ch/cyberduck/binding/application/NSOutlineView.java
  binding/src/main/java/ch/cyberduck/binding/application/NSTableView.java
  osx/src/main/java/ch/cyberduck/ui/cocoa/controller/BrowserController.java
  osx/src/main/java/ch/cyberduck/ui/cocoa/controller/InfoController.java
  osx/src/main/java/ch/cyberduck/ui/cocoa/controller/ProfilesPreferencesController.java
Labels: interface

#16284 Support delete using MFA in default implementation.
  s3/src/main/java/ch/cyberduck/core/s3/S3DefaultDeleteFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3MoveFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3MultipleDeleteFeature.java
  s3/src/main/java/ch/cyberduck/core/s3/S3Session.java
  s3/src/main/java/ch/cyberduck/core/s3/S3ThresholdDeleteFeature.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/CopyWorkerTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/CryptoS3SingleTransferWorkerTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/MoveWorkerTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3DirectoryFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3MoveFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3MultipartUploadServiceTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3MultipartWriteFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3ObjectListServiceTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3SingleUploadServiceTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3TouchFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3VersioningFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/cryptomator/S3WriteFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/kms/KMSEncryptionFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/restore/GlacierTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3AccessControlListFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3AttributesFinderFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3BucketCreateServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3CopyFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3DefaultDeleteFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3DefaultMultipartServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3DirectoryFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3EncryptionFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3FindFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ListServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MetadataFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MoveFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MultipartCopyFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MultipartUploadServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3MultipartWriteFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ObjectListServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3PublicUrlProviderTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ReadFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3SearchFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3SingleUploadServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3StorageClassFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3ThresholdUploadServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3TimestampFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3TouchFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3TransferAccelerationServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3VersionedObjectListServiceTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3VersioningFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/s3/S3WriteFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/shared/CachingAttributesFinderFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/shared/CachingFindFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/shared/DefaultAttributesFinderFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/shared/DefaultDownloadFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/shared/DefaultFindFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/shared/DefaultTouchFeatureTest.java
  s3/src/test/java/ch/cyberduck/core/sts/AssumeRoleWithWebIdentityAuthorizationTest.java
  s3/src/test/java/ch/cyberduck/core/worker/MoveWorkerTest.java
  s3/src/test/java/ch/cyberduck/core/worker/S3SingleTransferWorkerTest.java
  spectra/src/test/java/ch/cyberduck/core/worker/SpectraSingleTransferWorkerTest.java
Labels: s3

#16285 Revised fix 78302f83 because of regression caused by f4466fcb.
  osx/src/main/java/ch/cyberduck/ui/cocoa/controller/InfoController.java
  windows/src/main/csharp/ch/cyberduck/ui/controller/InfoController.cs
Labels: s3

#16257 Add tests.
  ctera/src/test/java/ch/cyberduck/core/ctera/CteraMoveFeatureTest.java
Labels: ctera

#16290 Only disable preemptive authentication when response header value of …
  webdav/src/main/java/ch/cyberduck/core/dav/DAVSession.java
Labels: webdav

#16319 Fix #16318.
  googledrive/src/main/java/ch/cyberduck/core/googledrive/AbstractDriveListService.java
  googledrive/src/test/java/ch/cyberduck/core/googledrive/DriveWriteFeatureTest.java
Labels: googledrive

#16363 Revert designer deletion of selection change committed handler
  windows/src/main/csharp/ch/cyberduck/ui/winforms/PreferencesForm.Designer.cs
Labels: bug, interface, cyberduck
